services:
  - type: web
    name: video-calling-interview-platform
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && cd ../frontend && npm install && npm run build
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
