services:
  - type: web
    name: video-calling-interview-platform
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm install --prefix backend
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: node backend/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
